#!/usr/bin/bash

# Git
alias g="git status"
alias ga="git add"
alias gaa="git add --all"
# alias gc="git commit -m"
function gc() {
  git commit -S -m $1
}
alias gca="git commit -am"
alias gb="git branch"
alias gba="git branch -a"
alias gbd="git branch -d"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gf="git fetch"
alias gm="git merge"
alias gr="git rebase"
alias gl="git log"
alias gs="git show"
alias gd="git diff"
alias gbl="git blame"
alias gps="git push"
alias gpl="git pull --rebase"
alias grh="git reset --hard"
alias gss="git status -sb"

# TMUX
alias ta="tmux attach"
alias tls="tmux list-sessions"
alias tk="tmux kill-server"

# Personal
alias m="nvim"
alias gtest="./gradlew test"
alias amm="~/amm"
alias ggrep="ggrep --color=AUTO"

alias cssh="i2cssh"
